## *ExpenseTracker**

### Project Overview

**Motive / Goal**

This project is a simple **Personal Expense Tracker** built in Core Java with a Swing UI.

It allows you to:
- **Add new expenses** (amount, category, date)
- **View all expenses** 
- **Search expenses**
- **Sort expenses**(by amount, date, category, etc.)
- **View total spending**
- **Exit the application** 
- And also includes a Swing graphical user interface (GUI)

The main learning goal is to practice **Core Java**, **OOP concepts**, **Swing GUI**, **ArrayList**, and **File I/O** in one complete project.

---
### Tech Stack

- **Language**: Core Java (no frameworks)
- **UI**: Java Swing  
  (`JFrame`, `JPanel`, `JButton`, `JLabel`, `JTextField`, `JTable`, `JScrollPane`, `JTextArea`, `JOptionPane`)
- **In-memory storage**: `ArrayList<Expense>`
- (stores expenses while the program is running)
- **File storage**:Plain text file expenses.txt
- (used to save and load expenses on startup/exit)
-**Features supported**(Add Expense,View All Expenses,Search Expenses,Sort Expenses,View Total Expense,
Exit (Auto-save))

- **Not used**: Databases, Maven, Spring, Web servers, HTML/CSS, MySQL, Tomcat

---
### Project Structure
ExpenseTracker/
  src/
    models/
      Expense.java
    managers/
      ExpenseManager.java
    ui/
      MainMenu.java
      AddExpenseUI.java
      ViewExpensesUI.java
      SearchExpenseUI.java
      SortExpenseUI.java
      TotalExpenseUI.java
  storage/
    expenses.txt     (auto-created after adding expenses)
  out/               (compiled .class files generated by javac)
---
### Class-by-Class Explanation and Java Concepts
models/Expense.java

**Purpose** Represents one expense entry in the system.

**Java concepts**:
-Class and objects
-Private fields (encapsulation): amount, category, date, description
-Constructor to set all fields
-Getter methods for each private field
-toString() for readable text output

**Responsibilities**:
-Store data for a single expense.
-Convert expense fields to a single line of text when saving to file (e.g., "amount,category,date").
-Provide getters so other classes can read the values safely.
---
managers/ExpenseManager.java

**Purpose** Handles all expense operations and manages file saving/loading.

**Java concepts**:
-Collections: ArrayList<Expense>
-Sorting using Collections.sort() and custom comparators
-File I/O: File, FileReader, BufferedReader, FileWriter, BufferedWriter
-String splitting (.split(","))
-Exception handling with try-catch

**Responsibilities**:
-addExpense(Expense e): adds an expense and calls saveToFile() (auto-save).
-getAllExpenses(): returns the full list for the UI.
-searchExpenses(String keyword):
(Searches category, description, or date for matching text)
-sortByAmount():
(Sorts list in ascending order using a comparator).
-sortByDate():
(Sorts expenses by date (string comparison or converted date)).
-getTotalAmount():
(Loops through all expenses and returns the sum of amounts.)
-saveToFile():
(Creates storage/expenses.txt if missing.)
(Writes each expense on a separate line in amount,category,date,description format.)
-loadFromFile():
(Reads every line from the file.Splits by comma.
Reconstructs an Expense object for each line and adds it to the list.)
---
ui/MainMenu.java

**Purpose** The homepage window and main entry point of the program.

**Java concepts**:

-Swing basics: JFrame, JButton, JPanel, JLabel
-Layout managers: FlowLayout, GridLayout
-Event handling using ActionListener
-SwingUtilities.invokeLater() for safe UI launch

**Responsibilities**:
-Display the 6 main buttons:
Add Expense
View Expenses
Search
Sort
Total
Exit
-Open respective UI windows:
AddExpenseUI
ViewExpensesUI
SearchExpenseUI
SortExpenseUI
TotalExpenseUI
-Hold one shared ExpenseManager instance for the whole app.
-On Exit:
Save data
Close program
---
ui/AddExpenseUI.java

**Purpose**: Window where the user can add a new expense.

**Java concepts**:

-Swing: JLabel, JTextField, JButton, JOptionPane
-GridLayout for form-like structure
-Exception handling while parsing amount

**Responsibilities**:
-Show 4 input fields:
Amount
Category
Date
-Validate the input (check empty fields, ensure amount is a valid number).
-Create Expense object.
-Call expenseManager.addExpense() → auto-saves to file.
-Show a success popup.
-Clear inputs after adding.
---
ui/ViewExpensesUI.java

**Purpose** Window that displays all expenses in a table.

**Java concepts**:

-Swing table: JTable, DefaultTableModel, JScrollPane
-BorderLayout for centered table layout
-Looping through the expense list to populate rows

**Responsibilities**:
-Display columns:
Amount
Category
Date
-loadTableData():
Clear table.
Loop through every expense.
Add rows to the table model.
-Provide a Refresh button and a Close button.
---
ui/SearchExpenseUI.java

**Purpose** Window that allows searching expenses using a keyword.

**Java concepts**:

-Swing UI: JTextField, JButton, JTable
-Table population using DefaultTableModel
-String searching (contains, toLowerCase)

**Responsibilities**:
-Accept a search keyword from the user.
-Call expenseManager.searchExpenses(keyword).
-Display results in a table.
-If no results:
-Show a “No results found” popup.
---
ui/SortExpenseUI.java

**Purpose** Window where the user can sort expenses.

**Java concepts**:

-Buttons for different sort types
-Using sorted lists inside the table
-Comparators for amount/date sorting

**Responsibilities**:
-Provide two sorting options:
 Sort by Amount
 Sort by Date
-When the user clicks:
 Call the respective method in ExpenseManager.
 Reload table with sorted data.
-Provide a Close button.
---
ui/TotalExpenseUI.java

**Purpose** Simple window to show total amount spent.

**Java concepts**:

-Swing labels (JLabel)
-Basic math (sum from manager)
-BorderLayout

Responsibilities:
-Read the total using expenseManager.getTotalAmount().
-Display the value in a non-editable text label.
-Provide a Close button.
---
### How the Application Works (Feature Flow)
1.**Startup**
-MainMenu.main() is called.
-A new ExpenseManager is created.
-In its constructor, loadFromFile() is executed.
-If storage/expenses.txt exists, all previous expenses are loaded into an ArrayList<Expense>.

2.**Adding an Expense**
-User clicks “Add Expense” in MainMenu.
-AddExpenseUI opens.
-User enters amount, category, date, description, and clicks “Add”.
-A new Expense object is created and passed to expenseManager.addExpense().
-ExpenseManager adds it to the ArrayList and immediately calls saveToFile() to update expenses.txt.

3.**Viewing All Expenses**
-User clicks “View Expenses” in MainMenu.
-ViewExpensesUI opens and automatically calls loadTableData().
-All expenses from the ArrayList are displayed in a JTable.
-User can click “Refresh” after adding new expenses to reload updated data.

4.**Searching Expenses**
-User clicks “Search” in MainMenu.
-SearchExpenseUI opens.
-User enters any keyword (amount, category, date, description).
-Matching expenses are shown in a table.
-If no matches are found, a popup displays “No results found.”

5.**Sorting Expenses**
-User clicks “Sort” in MainMenu.
-SortExpenseUI opens.
-User can sort expenses either by:
 Amount
 Date
-After sorting, the sorted list is shown in a table.

6.**Viewing Total Expenses**
-User clicks “Total” in MainMenu.
-TotalExpenseUI opens.
-It calls expenseManager.getTotalAmount().
-The total of all expenses is displayed in a label or text area.

7.**Exiting**
-User clicks “Exit” in MainMenu.
-ExpenseManager.saveToFile() is called once more to ensure data is saved.
-The application closes using System.exit(0).
---

### How to Build and Run the Project
##Prerequisites
#### Step 1: Compile
Open **Command Prompt** and run:
---
cd /d D:\Github\SpendWise
javac -d out src\models\*.java src\managers\*.java src\ui\*.java
---
- This compiles all `.java` files and puts `.class` files into the `out` folder.

#### Step 2: Run
To make sure `storage/expenses.csv` is created under the project root `storage` folder
---
cd /d D:\Github\SpendWise
java -cp out MainMenu
---
- The **Personal Expense Tracker – Main Menu** window will open.
#### Step 3: Use the Application
**Enter details**
  - Fill in amount, category.
  - Click add to add expense.

- **View All Expenses**
  - Click **“View Expenses”**.
  - See all expenses in the table.
- **Search Expenses**
  - Click **"Search Expenses"**.
  - To search any expenses .
- **Sort Expenses**
  - Click **"Sort Expenses"**.
  - To sort any expenses category wise .

- **View Total**
  - Click **“Total”**.
  - See total expenses and category-wise totals.
- **Exit**
  - Click **“Exit”** to safely save and close the application.
---
   done by **Bhanu Jakka**